In [1]:
import numpy as np


# In[ ]:


def ellipsoid(x, alpha=1000):
    result = 0
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        for i in range(d):
             result = result + alpha**(i/(d-1))*x[i]**2
        return result
    else:
        result = x**2
        return result
    
def ellipsoid_gradient(x, alpha=1000):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result =  np.zeros(shape=d)
        for i, xi in enumerate(x, start= 1):   
            result[i-1] = alpha**((i-1)/(d-1))*2*xi
        return result
    else:
        return 2*x

def ellipsoid_hessian(x, alpha=1000):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result = np.zeros(shape=(d,d))
        for i in range(0,d):
            result[i,i] = alpha**(i/(d-1))*2
        return result
    else:
        return 2

def rosenbrockBanana(x):
    x1 = x[0]
    x2 = x[1]
    result = (1-x1) **2 + 100*(x2-x1**2)**2
    return result

def rosenbrockBanana_gradient(x):
    x1 = x[0]
    x2 = x[1]
    gradient_1 = -2*(1-x1)-400*x1*(x2-x1**2)
    gradient_2 = 200*(x2-x1**2)
    result = np.array([gradient_1, gradient_2])
    return result

def rosenbrockBanana_hessian(x):
    x1 = x[0]
    x2 = x[1]
    hessian_1_x1 = 2-400*(x2-3*x1**2)
    hessian_1_x2 = -400*x1
    hessian_2_x1 = -400*x1
    hessian_2_x2 = 200
    result = np.array([[hessian_1_x1, hessian_1_x2],[hessian_2_x1, hessian_2_x2]])
    return result

def log_ellipsoid(x, epsilon=10**(-4), alpha=1000):
    result = np.log(epsilon + ellipsoid(x, alpha))
    return result

def log_ellipsoid_gradient(x, epsilon=10**(-4), alpha=1000):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result =  np.zeros(shape=d)
        for i, xi in enumerate(x, start= 1):   
            result[i-1] = (alpha**((i-1)/(d-1))*2*xi) /(ellipsoid(x, alpha)+epsilon)
        return result
    else:
        return (2*x) /(ellipsoid(x, alpha)+epsilon)
    
def log_ellipsoid_hessian(x, epsilon=10**(-4), alpha=1000): 
    temp = ellipsoid(x, alpha)+epsilon
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result = np.zeros(shape=(d,d))
        for i in range(0,d):
            for j in range(0,d):
                if i == j:                 
                    result[i,j] = (2*alpha**(i/(d-1))*temp - (2*alpha**(i/(d-1))*x[i])**2) / temp**2
                else:
                    result[i,j] = -1*(2*alpha**(i/(d-1))*x[i])*(2*alpha**(j/(d-1))*x[j]) / temp**2
        return result
    else:
        return (2*temp - 4*x**2) / (temp**2)

def h(x, q):
    return (np.log(1 + np.exp(-np.abs(q*x))) +np.where(q*x < 0, 0, q*x))/q  

def attractive_sector(x, q=10**4):
    result = 0
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        for i in range(d):
            result = result + h(x[i],q)**2 + 100*h(-x[i],q)**2
        return result
    else:
        return h(x,q)**2 + 100*h(-x,q)**2

def h_gradient(x, q):
    if x>=0:
        return 1 - np.exp(-q*x)/(1+np.exp(-q*x))  
    else:
        return np.exp(q*x)/(1+np.exp(q*x)) 

def attractive_sector_gradient(x, q=10**4):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result =  np.zeros(shape=d)
        for i, xi in enumerate(x):   
            result[i] = 2*h_gradient(xi,q)*h(xi,q)-200*h_gradient(-xi,q)*h(-xi,q)
        return result
    else:
        return 2*h_gradient(x,q)*h(x,q)-200*h_gradient(-x,q)*h(-x,q)

def h_hessian(x, q):
    if x>=0:
        return (q*np.exp(-q*x))/(1+np.exp(-q*x))**2
    else:
        return (q*np.exp(q*x))/(1+np.exp(q*x))**2 
    
def attractive_sector_hessian(x, q=10**4): 
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result =  np.zeros(shape=(d,d))
        for i in range(d):   
            result[i, i] = 2*h_gradient(x[i],q)**2 + 2*h(x[i],q)*h_hessian(x[i],q) + 200*h_gradient(-x[i],q)**2 + 200*h(-x[i],q)*h_hessian(-x[i],q)
        return result
    else:
        return 2*h_gradient(x,q)**2 + 2*h(x,q)*h_hessian(x,q) + 200*h_gradient(-x,q)**2 + 200*h(-x,q)*h_hessian(-x,q)
    
def different_power(x):
    result = 0 
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        for i in range(d):
             result = result + x[i]**(2+2*i/(d-1))
        return result
    else:
        return x**2
    
def different_power_gradient(x):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result =  np.zeros(shape=d)
        for i, xi in enumerate(x):   
            result[i] = 2*(1+i/(d-1))*xi**(1+2*i/(d-1))
        return result
    else:
        return 2*x

def different_power_hessian(x):
    if isinstance(x, (list, np.ndarray)):
        d = len(x)
        result = np.zeros(shape=(d,d))
        for i in range(0,d):
            result[i,i] = 2*(d+i-1)*(d+2*i-1)/(d-1)**2*x[i]**(2*i/(d-1))
        return result
    else:
        return 0



In [9]:
import traceback
from functools import partial

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

def line_search(fun,x,p,gradient,alpha=1,rho=0.2,c=1e-5, max_iter=100):
    for i in range(max_iter):
        term1 = fun(x + alpha * p)
        term2 = fun(x)+c*alpha*np.dot(gradient,p)
        if term1 <= term2:
            break

        alpha*=rho
    return alpha

def gradient_descent(fun,fun_d1,fun_d2,x,optimum,epsilon=1e-7,max_iter=20000, ret_fd=False):
    grad_norm_arr = np.zeros(max_iter)
    dist_arr = np.zeros(max_iter)
    f_diffs = np.zeros(max_iter)

    prev_f = fun(x) - fun(optimum)

    for i in range(max_iter):
        gradient=fun_d1(x)
        iteration = i + 1

        grad_norm_sq=np.linalg.norm(gradient) ** 2

        grad_norm = np.linalg.norm(gradient)
        dist = distance(x, optimum)
        grad_norm_arr[i] = grad_norm
        dist_arr[i] = dist

        direction=-gradient

        alpha = line_search(fun, x, direction, gradient, alpha=0.1)
#         alpha = line_search(fun, x, direction, gradient)
        new_x = x + alpha*direction
        if ret_fd:
            # print((fun(new_x) - fun(optimum)))
            f_diffs[i] = (fun(new_x) - fun(optimum)) / prev_f
            prev_f = f_diffs[i]
        x = new_x

        if grad_norm_sq<epsilon:
            break

    if ret_fd:
        return iteration, f_diffs
    return x, iteration, grad_norm_arr, dist_arr

def gradient_descent_sq(fun,fun_d1,fun_d2,x,optimum, Q, epsilon=1e-7,max_iter=20000, ret_fd=False):
    grad_norm_arr = np.zeros(max_iter)
    dist_arr = np.zeros(max_iter)
    f_diffs = np.zeros(max_iter)

    prev_f = fun(x) - fun(optimum)

    for i in range(max_iter):
        gradient=fun_d1(x)
        iteration = i + 1

        grad_norm_sq=np.linalg.norm(gradient) ** 2

        grad_norm = np.linalg.norm(gradient)
        dist = distance(x, optimum)
        grad_norm_arr[i] = grad_norm
        dist_arr[i] = dist

        direction=-gradient

        # alpha = line_search(fun, x, direction, gradient, alpha=0.1)
        alpha = (gradient @ gradient) / (gradient @ Q @ gradient)
        print(alpha)

        new_x = x + alpha*direction
        if ret_fd:
            # print(fun(new_x) - fun(optimum))
            f_diffs[i] = (fun(new_x) - fun(optimum)) / prev_f
            prev_f = f_diffs[i]
        x = new_x

        if grad_norm_sq<epsilon:
            break

    if ret_fd:
        return iteration, f_diffs
    return x, iteration, grad_norm_arr, dist_arr

def changeH(A, beta=1e-2, max_k=100):
    diag = np.diagonal(A)
    if np.min(diag) > 0:
        tau_k = 0
    else:
        tau_k = -np.min(diag) + beta
    for k in range(max_k):
        res = A + tau_k * np.identity(A.shape[0])
        try:
            _ = np.linalg.cholesky(res)
            return res
        except:
            tau_k = max(2 * tau_k, beta)
    return res


def newton(fun,fun_d1,fun_d2,x,optimum,epsilon=1e-7,max_iter=20000):
    grad_norm_arr = np.zeros(max_iter)
    dist_arr = np.zeros(max_iter)
    iteration = 0
    for i in range(max_iter):
        iteration += 1
        gradient = fun_d1(x)
        hessian=fun_d2(x)
        hessian=changeH(hessian)
        hessian_inv=np.linalg.inv(hessian)

        direction=-np.dot(hessian_inv,gradient)
        grad_dot=np.dot(np.dot(gradient,hessian_inv),gradient)

        grad_norm = np.linalg.norm(gradient)
        dist = distance(x, optimum)
        grad_norm_arr[i] = grad_norm
        dist_arr[i] = dist

        alpha = line_search(fun, x, direction, gradient, rho=0.5)
        x += alpha * direction

        # print(x)
        if grad_dot < epsilon:
            break

    return x, iteration, grad_norm_arr, dist_arr


def performanceMessure(funs,funs_d1,funs_d2,funs_min,algos, n_repeats=10, box_size=10):
    n_algos = len(algos)
    n_funs = len(funs)
    accuracy = np.zeros((n_algos, n_funs, n_repeats))
    efficiency = np.zeros((n_algos, n_funs, n_repeats))
    robustness= np.zeros((n_algos, n_funs, n_repeats))
    grad_norm_acc = []
    dist_acc = []

    for i, fun in enumerate(funs):
        print("FUN: {}".format(fun.__name__))
        grad_norm_acc1 = []
        dist_acc1 = []
        for j in range(n_repeats):
            grad_norm_acc2 = []
            dist_acc2 = []
            for z,algo in enumerate(algos):
                x = np.random.uniform(-box_size, box_size, 2)
                newx, iteration, grad_norm_arr, dist_arr = algo(funs[i],
                                                                funs_d1[i],
                                                                funs_d2[i],
                                                                x,
                                                                funs_min[i])
                accuracy[z,i,j] = distance(newx,funs_min[i])
                efficiency[z,i, j] = iteration
                robustness[z,i, j] = 1
                grad_norm_acc2.append(grad_norm_arr)
                dist_acc2.append(dist_arr)

            grad_norm_acc1.append(grad_norm_acc2)
            dist_acc1.append(dist_acc2)
        grad_norm_acc.append(grad_norm_acc1)
        dist_acc.append(dist_acc1)
    accuracy = np.mean(accuracy, axis=2)
    efficiency = (np.mean(efficiency, axis=2)).astype(int)
    robustness = np.mean(robustness, axis=2)
    grad_norm_acc = np.array(grad_norm_acc).mean(axis=2)
    dist_acc = np.array(dist_acc).mean(axis=1)
    # grad_norm_acc = np.array(grad_norm_acc).median(axis=2)
    # dist_acc = np.array(dist_acc).median(axis=1)

    return accuracy,efficiency,robustness,grad_norm_acc,dist_acc


def distance(p1,p2):
    return np.sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2)


def plotgraph(Y, methods, y_label, plot_name, log, max_x_factor=1):
    labels=[r"$f_1$ The Ellipsoid function",r"$f_2$ The Rosenbrock Banana Function",
            r"$f_3$ The Log-Ellipsoid Function",r"$f_4$ The Attractive-Sector Function",
            r"$f_5$ The Sum of Different Powers Function"]
    colors=["red", "blue"]
    fig = plt.figure(figsize=(20,10))
    for i, label in enumerate(labels):
        ax = fig.add_subplot(2, 3, i+1)
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.set_title(label)
        plt.xlabel("number of iterations")
        plt.ylabel(y_label)
        for j, method in enumerate(methods):
            y = Y[i,0]
            max_y = y[y>0].shape[0] * max_x_factor
            if log:
                # ax.plot(range(1, max_y+1), np.log(Y[i,j,:max_y] + 1e-7), color=colors[j], label=method)
                plt.yscale("log")
                plt.xscale("log")
                ax.plot(range(1, max_y+1), Y[i,j,:max_y], color=colors[j], label=method)
            else:
                ax.plot(range(1, max_y+1), Y[i,j,:max_y], color=colors[j], label=method)
        ax.legend()
    plt.subplots_adjust(hspace=0.4)
    # plt.show()
    plt.savefig("../images/plt01_{}.png".format(plot_name), bbox_inches ="tight")
    plt.clf()


def performanceMeassure2(fun, fun_d1, fun_min, alphas, d=5, n_tries=100):
    d_fs = []
    bounds = []
    for j, alpha in enumerate(alphas):
        f_diffs_acc = []
        max_iter_acc = []
        Q = np.diag(alpha ** np.arange(5))
        for i in range(n_tries):
            x_start = np.random.uniform(-10, 10, d)
            fun_p = partial(fun, alpha=alpha, d=d)
            fun_d1_p = partial(fun_d1, alpha=alpha, d=d)
            # n_runs, f_diffs = gradient_descent_sq(fun_p, fun_d1_p, None, x_start, fun_min, Q, ret_fd=True)
            n_runs, f_diffs = gradient_descent(fun_p, fun_d1_p, None, x_start, fun_min, ret_fd=True)
            f_diffs_acc.append(f_diffs)
            max_iter_acc.append(n_runs)

        max_iter = np.array(max_iter_acc).mean().astype(int)
        f_diffs = np.array(f_diffs_acc).mean(axis=0)
        f_diffs[1::2] = f_diffs[::2]

        bound_val = ((alpha-1)/(alpha+1))**2
        bound = np.repeat(bound_val, max_iter)
        d_fs.append(f_diffs[:max_iter])
        bounds.append(bound)
    return d_fs, bounds


def plot_bounds(d_fs, bounds, alphas, log=False):
    colors = ["yellow", "blue", "red", "green",  "blue"]
    fig = plt.figure(figsize=(15, 15))
    # fig = plt.figure()
    for alpha, color, i in zip(alphas, colors, range(len(alphas))):
        ax = fig.add_subplot(len(d_fs), 3, i+1)
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.set_title(r"$\kappa(Q)={}$".format(alpha))
        plt.xlabel("k")
        # plt.ylabel("bound")
        # plt.ylabel(r"$\frac{f(x_{k+1}) - f(x^*))}{f(x_{k} - x^*)}$")
        plt.ylabel(r"$\Delta$ dist to $f(x^*)$")
        if log:
            plt.yscale("log")
        xs = np.arange(d_fs[i].shape[0])
        plt.plot(xs, d_fs[i], color=color, label=r"$g(k)$")
        plt.plot(xs, bounds[i], color=color, linestyle="--", label=r"bound = {:06.4f}".format(bounds[i][0]))
        ax.legend()
    plt.subplots_adjust(hspace=0.45)
    plt.savefig("../images/plt01_bound.png", bbox_inches ="tight")
    plt.show()


def main():
    funs = [ellipsoid, rosenbrockBanana, log_ellipsoid, attractive_sector, different_power]

    funs_d1 = [ellipsoid_gradient, rosenbrockBanana_gradient, log_ellipsoid_gradient, attractive_sector_gradient, different_power_gradient]

    funs_d2 = [ellipsoid_hessian, rosenbrockBanana_hessian, log_ellipsoid_hessian, attractive_sector_hessian, different_power_hessian]
    funs_min = [[0, 0], [1, 1], [0, 0], [0, 0], [0, 0]]

    algos=[gradient_descent,newton]
    methods=["Steepest Descent","newton"]
    # algos=[newton]
    # methods=["newton"]

    accuracy, efficiency, robustness, grad_norms, dists = performanceMessure(funs,
                                                                            funs_d1,
                                                                            funs_d2,
                                                                            funs_min,
                                                                            algos,
                                                                            n_repeats=100)
    print(accuracy)
    print(efficiency)
    print(robustness)

    # plothist(accuracy, methods, "dist", "Accuracy")

    plotgraph(grad_norms, methods, r"$||\nabla f||$", "grad", log=False)
    # # plotgraph(dists, methods, r"$\log($dist$)$", "dist", log=True)
    plotgraph(dists, methods, r"$distance$", "dist", log=True)

    fun = ellipsoid
    fun_d1 = ellipsoid_gradient
    alphas = np.array([10**i for i in [1,2,3]])
    # alphas = np.array([10])

    d_fs, bounds = performanceMeassure2(fun, fun_d1, np.repeat(0, 5), alphas, n_tries=100)
    # d_fs, bounds = performanceMeassure2(fun, fun_d1, np.repeat(0, 5), alphas, n_tries=1)
    plot_bounds(d_fs, bounds, alphas, log=True)


if __name__ == '__main__':
    DEBUG = False
    main()

FUN: ellipsoid
FUN: rosenbrockBanana
FUN: log_ellipsoid
FUN: attractive_sector
FUN: different_power
[[1.43530904e-04 8.28427888e-04 6.30750058e-09 2.77291973e-04
  4.21342478e-02]
 [0.00000000e+00 7.47535030e-08 3.81936403e-15 2.49143600e-04
  9.24549811e-03]]
[[3409 6803 2101   51  618]
 [   2   32   18    4   14]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


TypeError: ellipsoid() got an unexpected keyword argument 'd'

<Figure size 1440x720 with 0 Axes>

<Figure size 1440x720 with 0 Axes>